# Generated by Django 5.0.4 on 2024-04-30 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minorproject', '0003_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Allergies',
        ),
    ]
