# Generated by Django 5.0.4 on 2024-05-05 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minorproject', '0007_allergies_careplans_conditions_devices_doctordoctor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patients',
            options={},
        ),
    ]
