# Generated by Django 5.0.4 on 2024-05-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minorproject', '0008_alter_patients_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patients',
            options={'managed': False},
        ),
    ]
