# Generated by Django 5.0.4 on 2024-05-05 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minorproject', '0010_medication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medication',
        ),
    ]
