# Generated by Django 5.0.4 on 2024-04-18 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='medical',
        ),
    ]
