# Generated by Django 5.0.4 on 2024-04-18 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_doctor_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='blood',
        ),
    ]
